package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

const (
	agenticProgressSummaryLimit      = 4000
	agenticContinuityManifestLimit   = 12 * 1024
	agenticCommandBuilderResultLimit = 24 * 1024
	agenticCommandDisplayPromptLimit = 2 * 1024
)

func boundAgenticContinuityText(value string, limit int) string {
	value = strings.TrimSpace(value)
	if value == "" || limit <= 0 || len(value) <= limit {
		return value
	}
	bounded, _ := truncateAgenticHeadTailText(value, limit)
	return strings.TrimSpace(bounded)
}

func (a *App) prepareAgenticTaskContinuity(projectName, taskID, prompt string, automaticContinuation bool) (agenticWorkspaceTask, error) {
	taskRoot, err := a.agenticWorkspaceTaskRoot(projectName, taskID)
	if err != nil {
		return agenticWorkspaceTask{}, err
	}
	task, err := loadAgenticWorkspaceTask(taskRoot)
	if err != nil {
		return agenticWorkspaceTask{}, err
	}
	if task.ProjectName != projectName {
		return agenticWorkspaceTask{}, fmt.Errorf("agentic workspace belongs to another project")
	}
	prompt = strings.TrimSpace(prompt)
	if task.OriginalPrompt == "" && prompt != "" {
		task.OriginalPrompt = prompt
	}
	if !automaticContinuation && prompt != "" {
		task.LatestUserInstruction = prompt
	}
	if task.LatestUserInstruction == "" {
		task.LatestUserInstruction = task.OriginalPrompt
	}
	if err := saveAgenticWorkspaceTask(taskRoot, task); err != nil {
		return agenticWorkspaceTask{}, err
	}
	return loadAgenticWorkspaceTask(taskRoot)
}

func (a *App) saveAgenticLatestCommandResult(projectName, taskID, result string) (agenticWorkspaceTask, error) {
	taskRoot, err := a.agenticWorkspaceTaskRoot(projectName, taskID)
	if err != nil {
		return agenticWorkspaceTask{}, err
	}
	task, err := loadAgenticWorkspaceTask(taskRoot)
	if err != nil {
		return agenticWorkspaceTask{}, err
	}
	if task.ProjectName != projectName {
		return agenticWorkspaceTask{}, fmt.Errorf("agentic workspace belongs to another project")
	}
	task.LatestCommandResult = boundAgenticContinuityText(result, agenticCommandBuilderResultLimit)
	if err := saveAgenticWorkspaceTask(taskRoot, task); err != nil {
		return agenticWorkspaceTask{}, err
	}
	return loadAgenticWorkspaceTask(taskRoot)
}

func agenticWorkspaceManifestPrompt(review agenticWorkspaceReview) string {
	if review.Deleted {
		return "- Staged workspace resolved and removed."
	}
	if len(review.Changes) == 0 {
		return fmt.Sprintf("- No staged file differences. Unchanged files: %d.", review.UnchangedCount)
	}
	changes := append([]agenticWorkspaceChange(nil), review.Changes...)
	sort.Slice(changes, func(i, j int) bool { return changes[i].Path < changes[j].Path })
	lines := []string{fmt.Sprintf("- Counts: added=%d modified=%d deleted=%d pending=%d conflicts=%d unchanged=%d", review.AddedCount, review.ModifiedCount, review.DeletedCount, review.PendingCount, review.ConflictCount, review.UnchangedCount)}
	for index, change := range changes {
		line := fmt.Sprintf("- %s: %s [%s]", strings.ToUpper(change.Kind), change.Path, change.Decision)
		if change.Conflict {
			line += " CONFLICT: " + change.ConflictReason
		}
		candidate := strings.Join(append(lines, line), "\n")
		if len(candidate) > agenticContinuityManifestLimit {
			remaining := len(changes) - index
			lines = append(lines, fmt.Sprintf("- ... %d additional staged change(s) omitted from continuity context.", remaining))
			break
		}
		lines = append(lines, line)
	}
	return strings.Join(lines, "\n")
}

func agenticEnvironmentWorkspacePrompt(workspace map[string]any) string {
	if workspace == nil {
		workspace = map[string]any{}
	}
	data, err := json.MarshalIndent(workspace, "", "  ")
	if err != nil {
		return "{}"
	}
	return string(data)
}

func buildAgenticTaskContinuityMessage(task agenticWorkspaceTask, review agenticWorkspaceReview) string {
	original := strings.TrimSpace(task.OriginalPrompt)
	if original == "" {
		original = "(not recorded; preserve current task intent from available context)"
	}
	latestUser := strings.TrimSpace(task.LatestUserInstruction)
	if latestUser == "" {
		latestUser = "(no later user instruction)"
	}
	progress := strings.TrimSpace(task.ProgressSummary)
	if progress == "" {
		progress = "(first turn; no prior progress summary)"
	}
	latestCommand := strings.TrimSpace(task.LatestCommandResult)
	if latestCommand == "" {
		latestCommand = "(no command result yet)"
	}
	maxRuns := task.MaxRuns
	if maxRuns <= 0 {
		maxRuns = 50
	}
	return strings.TrimSpace(fmt.Sprintf(`AGENTGO AGENTIC TASK CONTINUITY

ORIGINAL USER TASK — preserve verbatim intent:
%s

LATEST USER INSTRUCTION OR ANSWER:
%s

ROLLING CUMULATIVE PROGRESS SUMMARY — Ugg Protocol, terse but complete:
%s

ENVIRONMENT WORKSPACE JSON — command-verified facts carried across turns:
%s

CURRENT STAGED-CHANGE MANIFEST — generated by AgentGO:
%s

LATEST TERMINAL DECISION / COMMAND RESULT:
%s

TASK CONTROL STATE:
- Mode: %s
- Run: %d of %d
- Workspace status: %s

Continue this same staged task. Use current staged files as source of truth. Do not assume canonical projectwork contains staged changes. Return an updated cumulative summary in summary on every agentic response.`, original, latestUser, progress, agenticEnvironmentWorkspacePrompt(task.Workspace), agenticWorkspaceManifestPrompt(review), latestCommand, task.Mode, task.RunNumber, maxRuns, task.Status))
}

func buildAgenticCommandResultPrompt(title, decision string, task *agenticWorkspaceTask, command workModeAgenticCommand, execution *agenticExecutionResult, automatic bool) string {
	lines := []string{boundAgenticContinuityText(title, 512)}
	if task != nil {
		maxRuns := task.MaxRuns
		if maxRuns <= 0 {
			maxRuns = 50
		}
		lines = append(lines, fmt.Sprintf("Run: %d of %d", task.RunNumber, maxRuns))
	}
	if strings.TrimSpace(decision) != "" {
		lines = append(lines, "Decision: "+boundAgenticContinuityText(decision, 1024))
	}
	lines = append(lines,
		"Purpose: "+boundAgenticContinuityText(command.Purpose, 2*1024),
		"Working directory: "+boundAgenticContinuityText(command.WorkingDirectory, 1024),
		"Command type: "+boundAgenticContinuityText(command.Type, 128),
		"Command: "+boundAgenticContinuityText(agenticManualCommandDisplay(command), agenticCommandDisplayPromptLimit),
	)
	if execution == nil {
		lines = append(lines, "", "The command was denied and was not executed.")
	} else {
		lines = append(lines, "", "Execution status: "+boundAgenticContinuityText(execution.Status, 128), fmt.Sprintf("Duration: %d ms", execution.DurationMillis))
		if execution.ExitCode != nil {
			lines = append(lines, fmt.Sprintf("Exit code: %d", *execution.ExitCode))
		}
		if execution.TimedOut {
			lines = append(lines, "Timed out: true")
		}
		if execution.Cancelled {
			lines = append(lines, "Cancelled: true")
		}
		if execution.Error != "" {
			lines = append(lines, "Error: "+boundAgenticContinuityText(execution.Error, 4*1024))
		}
	}
	continuation := "Continue the same staged task using this user-controlled result. Canonical projectwork remains unchanged until user review and merge."
	if automatic {
		continuation = "Continue the same staged task automatically using this result. Canonical projectwork remains unchanged until user review and merge."
	}
	base := strings.Join(lines, "\n")
	suffix := "\n\n" + continuation
	if execution != nil {
		if excerpt := strings.TrimSpace(execution.AIOutputExcerpt); excerpt != "" {
			available := agenticCommandBuilderResultLimit - len(base) - len(suffix) - 2
			if available > 0 {
				excerpt = boundAgenticContinuityText(excerpt, available)
				base += "\n\n" + excerpt
			}
		}
	}
	result := base + suffix
	if len(result) > agenticCommandBuilderResultLimit {
		result, _ = truncateAgenticHeadTailText(result, agenticCommandBuilderResultLimit)
	}
	return strings.TrimSpace(result)
}
